#%RAML 1.0 ResourceType
post?:
  responses:
    200:
      body:
        application/json:
          type: <<item>>
get?:
  description: used to get information about item
  responses:
    200:
      body:
        application/json:
          type: <<item>>
type: standardResponse
put:
  description: used to update item
  body:
    application/json:
  responses:
    200:
      description: updated item
      body:
        application/json:
          type: <<item>>
delete:
