#%RAML 1.0 ResourceType
type: standardResponse
post:
  description: Allows to create new <<objectName | !singularize>>
  body:
    application/json:
      type: New<<objectName | !singularize>>
  responses:
    201:
      body:
        application/json:
          type: <<objectName | !singularize>>
